# Generated by Django 5.1.2 on 2024-10-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('authoer_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
